Arguments:
  MODE:[past|live]  Choose the mode in which you want to run tgcf.  [env var:
                    TGCF_MODE;required]


Options:
  -l, --loud     Increase output verbosity.  [env var: LOUD]
  -v, --version  Show version and exit.
  --help         Show this message and exit.
